---
- name: Gather Bucket Info
  hosts: all
  gather_facts: True
  validate_certs: True
  display_args_to_stdout: True
  log_path: /usr/local/ansilog/info_probe.txt
  tasks:
    - aws_s3_bucket_info:
      register: result
    - aws_region_info:
        filters:
          region-name: us-west-1
    - name: Lists all s3 buckets
      debug:
      msg: "{{ result['buckets'] }}"
    - name: Lambda Function Listout
      lambda_info:
        query: all
        max_items:30
