---
- name: Deploy using shell modules
  hosts: 172.18.35.50
  tasks:
    - name: Docker Deployment Via BASH
      command: /scripts/docker_init.sh
     
    - name: yum refresh of assets
      yum:
        name: '*'
        state: latest
  
    - name: Pull images for docker
      shell: docker pull linode/lamp
  
    - name: Run LAMP w/ port 80 forwarded
      shell: docker run --name lampcont -p 80:80 linode/lamp
  
    - name: Start apache and other mods
      shell: docker exec lampcont service apache2 start
  
    - name: Start Mysql
      shell: docker exec lampcont service mysql start
