---
- hosts: local
  connection: local
  gather_facts: no
  tasks:

      - name: Delete a EC2 key
        ec2_key:
            name: BDtest-key
            region: us-west-1
            state: absent
