- name: Yum Update Scheduler and Alerts Playbook
  hosts: all
  gather_facts: no
  become_user: root
  become: yes
  become_method: sudo

  tasks: 
    - name: all packages upgrade
      yum:
        name: '*'
        state: latest
        exclude: kernel*
        update_cache: yes
        skip_broken: yes
        download_only: true
