- name: Yum Update Scheduler and Alerts Playbook
  hosts: all
  gather_facts: no
  become_user: root
  become: yes
  become_method: sudo

  tasks: 
    - name: Pre-req packages for playbook
      yum:
        name:
          - postfix
          - yum-utils
        - state: present
    - name: all packages upgrade
      yum:
        name: '*'
        state: latest
        download_only: true
        exclude: kernel*
